### ISSUE TITLE
Erro na tradução do Filtro TreeView

### ISSUE THREAD

**Issue by hugocalvet** [pittufg/filter-tree-view#2]
**Erros:**

**1.** Ao invés de estar escrito "Count" em 'Ordenar por', o rótulo está escrito dessa forma "COM_FABRIK_SHOW_COUNT"
**2.** E na opção que deveria estar escrito "Sorted by", está escrito "COM_FABRIK_FIELD_SORTED_BY"

![Teste Filtro TreeView](https://user-images.githubusercontent.com/57194130/68044648-7e9d5b80-fcb6-11e9-8190-816fb5693980.png)

**Comment by karinepires6** [comment]
Resolved in 4e56745
