### ISSUE TITLE
Erro ao usar a função 'Limpar Filtros'

### ISSUE THREAD

**Issue by hugocalvet** [pittufg/filter-tree-view#5]
Erro:

- Ao clicar para Limpar Filtros no botão acima do painel de filtros na listagem de itens, não está limpando as categorias ja selecionadas na árvore.

**Comment by karinepires6** [comment]
Resolvido no novo release do com_fabrik no repositório [](https://github.com/pittufg/com_fabrik/releases/tag/v0.2-component)
